# Generated by Django 4.2.2 on 2023-06-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirLineCompanies',
            fields=[
                ('airLineId', models.BigAutoField(primary_key=True, serialize=False)),
                ('airLineName', models.TextField(max_length=100, unique=True)),
                ('companyLogo', models.ImageField(upload_to='images/usersPics/')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('CountryId', models.BigAutoField(primary_key=True, serialize=False)),
                ('CountryName', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('custId', models.BigAutoField(primary_key=True, serialize=False)),
                ('custFirstName', models.TextField(max_length=100)),
                ('custLastName', models.TextField(max_length=100)),
                ('custAdress', models.TextField(max_length=200)),
                ('custPhoneNum', models.TextField(max_length=100, unique=True)),
                ('custCreditCardNum', models.TextField(max_length=100, unique=True)),
                ('custPic', models.ImageField(upload_to='images/usersPics/')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flightId', models.BigAutoField(primary_key=True, serialize=False)),
                ('departureTime', models.DateTimeField()),
                ('landingTime', models.DateTimeField()),
                ('remainingTickects', models.IntegerField()),
                ('airLineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.airlinecompanies')),
                ('destinationCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flights', to='flghts_order_system.countries')),
                ('originCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_flights', to='flghts_order_system.countries')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.TextField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('userName', models.TextField(max_length=100, unique=True)),
                ('password', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=200, unique=True)),
                ('userRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticketId', models.BigAutoField(primary_key=True, serialize=False)),
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.customers')),
                ('flightId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.flights')),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.users'),
        ),
        migrations.AddField(
            model_name='airlinecompanies',
            name='countryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.customers'),
        ),
        migrations.AddField(
            model_name='airlinecompanies',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.users'),
        ),
        migrations.CreateModel(
            name='Adminstrators',
            fields=[
                ('adminId', models.BigAutoField(primary_key=True, serialize=False)),
                ('adminPic', models.ImageField(upload_to='images/usersPics/')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.users', unique=True)),
            ],
        ),
    ]
