# Generated by Django 4.2.2 on 2023-06-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirLineCompanies',
            fields=[
                ('air_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('air_line_name', models.CharField(max_length=100, unique=True)),
                ('company_logo', models.ImageField(default='', upload_to='images/companies_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('Country_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Country_name', models.CharField(max_length=200)),
                ('Country_flag', models.ImageField(default='', upload_to='images/countries_flags/')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cust_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cust_first_name', models.CharField(max_length=100)),
                ('cust_last_name', models.CharField(max_length=100)),
                ('cust_adress', models.CharField(max_length=200)),
                ('cust_phone_num', models.CharField(max_length=100, unique=True)),
                ('cust_credit_card_num', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('landing_time', models.DateTimeField()),
                ('remaining_tickects', models.IntegerField()),
                ('air_line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.airlinecompanies')),
                ('destination_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flights', to='flghts_order_system.countries')),
                ('origin_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_flights', to='flghts_order_system.countries')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=25, unique=True)),
                ('role_logo', models.ImageField(default='', upload_to='images/roles_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cust_idd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.customers')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.flights')),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.users'),
        ),
        migrations.AddField(
            model_name='airlinecompanies',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.customers'),
        ),
        migrations.AddField(
            model_name='airlinecompanies',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.users'),
        ),
        migrations.CreateModel(
            name='Adminstrators',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.users')),
            ],
        ),
    ]
