# Generated by Django 4.2.2 on 2023-07-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flghts_order_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='Country_flag',
            new_name='country_flag',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='Country_id',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='Country_name',
            new_name='country_name',
        ),
        migrations.AlterField(
            model_name='airlinecompanies',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.countries'),
        ),
    ]
