# Generated by Django 4.2.2 on 2023-06-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flghts_order_system', '0002_alter_adminstrators_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='role_id',
            new_name='roleId',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='role_name',
            new_name='roleName',
        ),
    ]
