# Generated by Django 4.2.2 on 2023-07-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flghts_order_system', '0002_rename_country_flag_countries_country_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='cust_idd',
            new_name='cust_id',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role_logo',
        ),
    ]
