# Generated by Django 4.2.2 on 2023-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flghts_order_system', '0003_rename_cust_idd_tickets_cust_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstrators',
            name='admin_first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adminstrators',
            name='admin_last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
