# Generated by Django 4.2.2 on 2023-08-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flghts_order_system', '0004_adminstrators_admin_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstrators',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.users'),
        ),
        migrations.AlterField(
            model_name='airlinecompanies',
            name='company_logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/companies_logos/'),
        ),
        migrations.AlterField(
            model_name='airlinecompanies',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.users'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flghts_order_system.users'),
        ),
    ]
