# Generated by Django 4.2.2 on 2023-09-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flghts_order_system', '0005_alter_adminstrators_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinecompanies',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='flghts_order_system.users'),
        ),
    ]
